### ISSUE TITLE
Do extension developer docs live here?

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/civicrm-dev-docs#10]
If we're to include extension developer docs here (which I think is a good idea), then we may need to restructure for this. Would that make sense? Something like,

```
.
├── docs
│   ├── api
│   │   ├── actions.md
│   │   ├── chaining.md
│   │   ├── general.md
│   │   ├── params.md
│   │   └── usage.md
│   ├── core
│   │   ├── contributing.md
│   │   ├── codestyle.md
│   │   ├── patches.md
│   │   └── review.md
│   ├── extending
│   │   ├── civix.md
│   │   └── hooks.md
```

**Comment by nganivet** [comment]
Makes sense. I would title the chapter 'Extensions' rather than 
extending mostly for SEO purposes (google: civicrm extensions developer 
documentation).

------ Original Message ------

**Comment by michaelmcandrew** [comment]
Agreed.
