### ISSUE TITLE
"community" page vs https://civicrm.org/help

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#100]
Quite a bit of overlap between these two pages: 

* https://civicrm.org/help
* https://docs.civicrm.org/dev/en/master/basics/community/

It would be nice to have one authoritative list of these community resources. I think this is the *third* time I've found the list in multiple places. (I already cleaned up the duplicate situation in a couple other places.) Having it on civicrm.org does make sense. Perhaps we move content there and link Dev Guide readers to that page? I'm not sure.

**Comment by michaelmcandrew** [comment]
I started off with the following:
> I think duplication is OK to some extent, but good if there is an obvious authoritative list.
>
> So perhaps we change the stuff in the dev guide to a short paragraph (2-4 sentences) that says something like
>
> "CiviCRM developers from around the globe use many systems to communicate and collaborate. The developer community is full of friendly people, eager to welcome newcomers. Mattermost and in-person events are great starting points if you're looking to get involved. For a full list of communication tools, see 
https://civicrm.org/help.*

But having looked at the two pages more closely, help is aimed at end users, whereas community is aimed at developers. and we don't want to scare users by exposing them to developer stuff.

That's not to say that there isn't a place on your website for a developer oriented list of resources (indeed there is a menu item at the bottom called developer resources) but I don't think we should merge it with user help.

So maybe move https://docs.civicrm.org/dev/en/master/basics/community/ to the website at civicrm.org/developer-resources?

**Comment by seanmadsen** [comment]
@michaelmcandrew what you said about audience being developer vs user makes sense. And when thinking about that, I think it does make sense to have two separate pages. And if there's a developer-focused page about resources, I think it *does* make sense to *keep* it in the Dev Guide. 

All of this leaves me with the opinion that the only real action necessary is to update the `civicrm.org/help` page with some more current info (e.g. don't highlight the forum, etc). I'll do this. 

And then if that's the only action needed, then I think we can close this issue. Will close in 24 hours if no further comments.
