### ISSUE TITLE
Document more Javascipt bindings for APIv3

### ISSUE THREAD

**Issue by totten** [civicrm/civicrm-dev-docs#120]
The [API: Usage](https://docs.civicrm.org/dev/en/master/api/usage/) docs describes several ways to use the API (3 PHP notations, 3 CLI notations, etc). For the Javascript related docs, I'd suggest:
 1. Rename `AJAX` to `Javascript (AJAX)`
 2. Add a section for `Javascript (AngularJS)`. (This uses `crmApi('MyEntity', 'myaction', {...}).then(...);`
 2. Add a section for `Javascript (Local NodeJS)`. Link to https://github.com/civicrm/cv-nodejs
 3. Add a section for `Javascript (Remote NodeJS)`. Link to https://github.com/TechToThePeople/node-civicrm

**Comment by seamuslee001** [comment]
See also https://github.com/civicrm/civicrm-dev-docs/pull/387
