### ISSUE TITLE
Document API joining

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#125]
API joining was introduced in 4.7 with [CRM-17795](https://issues.civicrm.org/jira/browse/CRM-17795). I think it deserves its own page in the Developer Guide, along with API Chaining, etc

There is already some documentation in [this PR comment](https://github.com/civicrm/civicrm-core/pull/7565#issuecomment-170631077). 

More content from the help box in the API explorer: 

> Join this api call to return values from or filter on a related entity. The new fields will be selectable from the "Params" and "Fields to return" lists. Example: If the api entity is Email, you can also fetch the display name of the contact this email belongs to. Disambiguation: Joins are different from api chaining in that joins execute as a single SELECT query, and only work for api "get" operations.

I think it'd be nice to create a page in the Dev Guide and then simplify the above help text to link to that page

**Comment by orubel** [comment]
The note was added 'post mention' of notification of a trademark violation after you were told to change 'api chaining(tm)' in the documentation. You and several other developers continued using the term in the interim.

The date you give is still post the original use of trademark in product.

**Comment by totten** [comment]
@orubel, the point of contact for trademark concerns is Josh Gowans -- with whom you are already in touch. Moreover, the chaining and joining techniques in APIv3 are different features working at different levels with different terminology and history. Your comment is off-topic.

As a community which uses public discussion for our day-to-day work, we rely on contributors to exercise discretion in keeping the conversation topical and productive. Of course, some miscommunication/variation/banter is inevitable, but most contributors exercise good judgment and good faith. Unfortunately, this is not the first time you've misused a procedure/channel. Please do not make a habit of it.

**Comment by orubel** [comment]
I have no idea what you are talking about per misuse of a channel but you wanting to 'argue' on a channel is misuse itself. 

Clarification of misuse of terms is completely normal. If you feel this requires a separate issue, please create one. I'm merely clarifying the misuse for the record.
