### ISSUE TITLE
Clarify intent re code overrides in criteria for reviewing extensions.

### ISSUE THREAD

**Issue by GinkgoFJG** [civicrm/civicrm-dev-docs#130]
Currently the criterion is: 

> The project does not override PHP, TPL, JS, or SQL from civicrm-core

It is clear to me how to override PHP or TPL code in an extension, but I am not aware of any way to replace core JS or SQL from an extension. So I guess the next questions are:

* Are there ways to do this, and if so what are they? Extension reviewers will need to know what to look for.
* If it's not currently possible, was the text was added because such capability is on the roadmap?
* If such capability is not on the roadmap, is there any reason not to delete JS and SQL from the sentence?

**Comment by GinkgoFJG** [comment]
Tagging @totten because I think the original language was his.

**Comment by totten** [comment]
Re: SQL - I've heard mention of extensions altering the schema of core tables. That's really what I intended.

Re: JS - You're right, there's no way to directly override JS. 

Would it better/clearer to have these out as a few separate requirements?

 * The project does not override PHP files or TPL files from `civicrm-core`.
 * The project does not modify the SQL schema of a standard `civicrm-core` table.

Or we could go the other direction -- more abstract:

 * The project respects the integrity of `civicrm-core` technical artifacts (PHP files, TPL files, SQL tables).

Or just:

 * Don't do evil hackery.

Although that last one might be a high bar. ;)

**Comment by seanmadsen** [comment]
I like what @totten suggested: 
>  * The project does not override PHP files or TPL files from `civicrm-core`.
> * The project does not modify the SQL schema of a standard `civicrm-core` table.
