### ISSUE TITLE
In meta-docs refer to "guides" instead of "books"

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#131]
We'd like to phase out the terminology of referring to documentation as "books", with the preference for calling them "guides" instead. 

Places that need to be changed: 

* [x] https://docs.civicrm.org/dev/en/latest/documentation/
* [ ] https://docs.civicrm.org/dev/en/latest/documentation/extensions/

Convo originally started by @michaelmcandrew [here](https://chat.civicrm.org/civicrm/pl/ksz16ognw3dxim6s8mmixh69pe)

**Comment by seanmadsen** [comment]
Related: https://github.com/civicrm/civicrm-docs/issues/56

**Comment by RonPainter** [comment]
I am working  on this issue, changing "book(s)" -> "guide(s)" depending on the context.

**Comment by seanmadsen** [comment]
Oh whoops I closed thinking that Ron's changes in #197 addressed this issue, but there's still one more page to work on &mdash; the [extensions docs](https://docs.civicrm.org/dev/en/latest/documentation/extensions/) page

**Comment by seanmadsen** [comment]
@RonPainter thanks for those changes! Can you do the same for the [extensions docs](https://docs.civicrm.org/dev/en/latest/documentation/extensions/) page? Then we can close this ticket.

**Comment by RonPainter** [comment]
Both files submitted (including extensions.md)
