### ISSUE TITLE
Migrate WSOD debugging info from SE

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#133]
Excellent content here, written by @xurizaemon 

https://civicrm.stackexchange.com/questions/6399/how-do-i-debug-civicrm-when-i-hit-a-blank-page-white-screen-fatal-error

It'd be great to bring some of that content into this page: 

https://docs.civicrm.org/dev/en/latest/dev-tools/debugging/

**Comment by seanmadsen** [comment]
Also incorporate this: 

https://civicrm.stackexchange.com/questions/17952/where-do-i-find-apache-error-logs-for-sites-that-i-installed-with-buildkit

**Comment by brucerinehart** [comment]
got these changes in pull request
next? just lemme know.. I'll look at the issues queue

**Comment by seanmadsen** [comment]
Closed with #163
