### ISSUE TITLE
getting started notes

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/civicrm-dev-docs#15]
hey

I'm just starting to learn civi extenstion writing and will try to assimilate "best" and "standard" practices...

where would be a good place to add such a page? (assuming we think this would be useful?)
many varied topics like:

* useful functions eg CRM_Core_Error::debug, CRM_Core_Error::debug_var
* useful constants eg CIVICRM_UF - eg "Drupal"
CIVICRM_SITE_KEY CIVICRM_TEMPLATE_COMPILEDIR CIVICRM_TEST_DIR CIVICRM_CLEANURL PATH_SEPARATOR DIRECTORY_SEPARATOR etc
 * best practice for file IO
* how to send a system email...

ie all the stuff that doesn't fit into the API  or hook pages

**Comment by seanmadsen** [comment]
This seems a bit general. With that, plus the time elapsed since last-activity, do you think we could close this ticket @ErichBSchulz ?

**Comment by ErichBSchulz** [comment]
sure!
