### ISSUE TITLE
Migrate SE content: (FAQ) How to choose a hosting environment

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/civicrm-dev-docs#170]
It's clear we could give some advice on how to select an appropriate VPS / hosting environment based on CiviCRM needs / estimated size / usage.

Generally users seem to ask "I have XXX contacts, so how big a VPS will fit them?".

IMO the reply often boils down to "But what are you doing with them? BTW, do you use smart groups for ACLs?"

See for example:

  * https://civicrm.stackexchange.com/questions/3287/number-of-contacts-vs-hosting-space-required?rq=1
  * https://civicrm.stackexchange.com/questions/6467/choosing-a-vps-solution-for-civicrm?noredirect=1&lq=1
  * https://civicrm.stackexchange.com/questions/11346/problem-with-civicrm-configuration-auto-increment-with-wordpress-4-x-website/11354#11354 (make sure the provider supports Civi's SQL demands)
  * https://civicrm.stackexchange.com/questions/11471/website-hosting-and-civicrm
  * https://civicrm.stackexchange.com/questions/17191/new-to-civicrm-hosting-vps-requirements-and-migration-from-nationbuilder?rq=1
  * https://civicrm.stackexchange.com/questions/18355/is-civicrm-resource-intensive?noredirect=1&lq=1
  * https://civicrm.stackexchange.com/questions/18503/is-1gb-memory-enough-for-small-server?noredirect=1&lq=1
  * https://civicrm.stackexchange.com/questions/18668/capacity-planning?noredirect=1&lq=1

This will be a bit of a hot topic with many invested partners being hosting providers, so we need to tread carefully and advise people to take advice / do own research.

**Comment by seamuslee001** [comment]
Just a thought is this better in the sysadmins guide @seanmadsen

**Comment by seanmadsen** [comment]
Agreed @seamuslee001. I wish there were a way to move tickets from one project to another. (GitLab has that feature!) For now I'm moving this ticket by closing this one and opening https://github.com/civicrm/civicrm-sysadmin-guide/issues/40
