### ISSUE TITLE
Clarifications for the Style Guide

### ISSUE THREAD

**Issue by stevekessler** [civicrm/civicrm-dev-docs#173]
While working on some documentation recently I found myself looking to the Style Guide (https://docs.civicrm.org/dev/en/master/best-practices/documentation-style-guide/) and not finding the clarity I was looking for. 

1.  Is there an expected way to link to an external link.  For example a link to a specific WordPress extension 
2. We say that "Elements of the system and interface should be capitalized" but should the name of a text field be bold?  We use bold for things you click in but what about the names of fields?  Is the **Button Title Field** or the Button Title Field? 
3.  Also, should the _Edit Widget Colors_ be bolded in the phrase "expand the Edit Widget Colors fieldset."?
4.  Is there a way that we should write CMS specific nomenclature?  For example a Drupal Block, WordPress Widget, etc.? 

You can look at https://docs.civicrm.org/user/en/latest/contributions/widgets/ to see where these examples started from?

Thanks,
Steve

**Comment by seanmadsen** [comment]
@stevekessler Cool. I'm all for making the Style Guide clearer! My thoughts on each of your questions...

### 1. External links

I'm not really sure what you're asking here. For example, here's how I'd link to a WordPress plugin: 

> [Caldera Forms CiviCRM](https://github.com/mecachisenros/caldera-forms-civicrm) is a WordPress plugin that integrates the [Caldera Forms plugin](https://wordpress.org/plugins/caldera-forms/) with CiviCRM.

### 2. and 3. How to style names of form elements

I agree that we could use more clarity here. I don't have opinions about what the Style Guide should say. Want to propose something?

### 4. CMS specific nomenclature 

Also not sure quite what you're asking here either? Can you offer some alternatives for us to choose from, as an example of what sort of clarity you're seeking?

**Comment by stevekessler** [comment]
@seanmadsen , 

1.  We are talking about the same thing.  I did what you did but did not know if we needed to somehow indicate that it is an external site.  

2. and 3.  In my own training and support writing "style" I use italics.  I think using italics for something you see and bold for something you click would be very clear.  Right now the guide calls for bold for something you click. A collapsed fieldset would still be ambiguous because it is sort of both.  

4. It is not that I do not think that writing Drupal Block is clear. In some other places and of course I cannot think of them off the top of my head now I have seen that they have specific formatting or standards around how they write about the way their tools interact with other technologies.  

-Steve

**Comment by seanmadsen** [comment]
`1.` Ahh, I see now. I like the idea to "indicate that it is an external site". Markdown gives us very little control over style (which I like), so the best way to implement your idea would be to do it programmatically for *all* hyperlinks by making a change to the theme. To this end, I've [created a new ticket here](https://lab.civicrm.org/documentation/docs-publisher/issues/66) to track progress on this goal. 

`4.` How about this: when you think of something specific to suggest, create a new ticket in this repo and we'll decide on it at that point, separately from the other ideas in this ticket. 

`2.` and `3.` I like it. 

### Next steps

For the purposes of this ticket I think `1.` and `4.` are now resolved, and `2.` and `3.` have become the same thing which requires more work. To keep this discussion more organized and and less demanding of people's time to read and figure out, I moved the `2.`/`3.` discussion to its own ticket: #174
