### ISSUE TITLE
overall migration strategy

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/civicrm-dev-docs#18]
I think we need to clarify the migration strategy from confluence.

If the confluence wiki is indeed deprecated then its banner should be changed to relfect this with a link to this repo.

and if this wiki is the replacement for confluence then we should clearly state that in the opening of the main page

I'm happy to make the changes and do a PR - but just want to clarify the above is actually correct before doing so

**Comment by michaelmcandrew** [comment]
a migration strategy is taking place on the wiki here: https://wiki.civicrm.org/confluence/display/CRMDOC/Content+migration+from+wiki+to+Developer+Guide

**Comment by seanmadsen** [comment]
-   Banner is up on this wiki page: [Develop](https://wiki.civicrm.org/confluence/display/CRMDOC/Develop) *(if you think we need banners on other pages, please open separate issue)*
-   [Migration strategy](https://wiki.civicrm.org/confluence/display/CRMDOC/Content+migration+from+wiki+to+Developer+Guide) is laid out *(as Michael pointed out)*
-   Dev Guide also points people to migration strategy page on the [documentation](https://docs.civicrm.org/dev/en/master/documentation/) page and the [home](https://docs.civicrm.org/dev/en/master/) page

Thus, I'm closing this issue.

**Comment by ErichBSchulz** [comment]
Thanks Sean! Personally I would like the banner on all pages but only if others think it would be good.
