### ISSUE TITLE
Document secure coding practices

### ISSUE THREAD

**Issue by MegaphoneJon** [civicrm/civicrm-dev-docs#188]
We should document best practices for security - comparable to https://drupal.org/writing-secure-code, https://developer.wordpress.org/plugins/security/ and http://docs.joomla.org/Secure_coding_guidelines.

It's my sense that this and #187 could be combined into a "Best Practices" page.

**Comment by nganivet** [comment]
Agreed, but would prefer to have this as a separate page since this is a key topic and it requires very specific tactics. This page of course will be referenced from the Best Practices and other pages.

**Comment by seamuslee001** [comment]
I have started work here https://github.com/civicrm/civicrm-dev-docs/pull/245 it contains information on security stuff e.g. ACL and Permission but does have a page on secure coding standards. Feedback most welcome

**Comment by seanmadsen** [comment]
Resolved with #245
