### ISSUE TITLE
Document civibuild "universe" build type

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#195]
You can use `civibuild` to install a "universe" build which has all extensions in it. This is very useful but, as far as I can tell, not documented anywhere. I propose adding a section on the [civibuild](https://docs.civicrm.org/dev/en/latest/tools/civibuild/) page which describes it, including describing the process of *updating* your universe build. 

*It was hard to resist titling this issue "Document the universe"* :wink:

**Comment by totten** [comment]
It is really hard to avoid riffing on that, eg "The Universe: A developer's guide" or "The User's Guide to the Universe".

Documenting this is a good idea. I may take a quick stab at it on the plane.

FWIW, when I first wrote that script, we had a small thread on `civicrm-dev` list. But `sympa` makes it hard to share links to those discussions. :(

In the context of `civibuild`, it's fairly straight-forward to mention it as a build-type. It works like any other build-type (`civibuild create universe`)

Note: There are lots of funny things... like Drupal+CiviCRM... that `civibuild` can create, but we don't put their docs under `civibuild`. For the longer pitch about when/why/how to use the `universe`, it might make sense to add a new entry "Tools => Universe" (at the same level as "Tools => Jenkins", "Tools => PhpStorm", etc).
