### ISSUE TITLE
Add preview heading to 'How to document your extension'

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-dev-docs#238]
Hi there,

I accidentally committed the following two commits to the master branch instead of creating a PR. I'm creating this issue in retrospect in case there is any disucssion to be had. Otherwise, we can just close it

https://github.com/civicrm/civicrm-dev-docs/commit/7d4736722495ae581ea13cf1bd168de6d18e9d5f
https://github.com/civicrm/civicrm-dev-docs/commit/530fba7206d4cced6d5f8ce96f1483dbe7abecab

**Comment by seanmadsen** [comment]
Looks good :slightly_smiling_face:
