### ISSUE TITLE
Do we want to promote markdown code standards?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#24]
The purpose of this issue is to make a group decision on whether or not to suggest markdown code standards to editors of the guides written in mkdocs. To keep it simple, let's just say there are two options: 

-   **Yes**, suggest markdown code standards
-   **No**, allow editors to use markdown as they see fit

if the group decides "no" here, then I think we can close this issue with no further action.  

If the group decides "yes" then we can create *separate issues* in this repo to make specific decisions regarding the contents of the code standards. For example, here are some questions on which we could seek clarity in (hypothetical) markdown code standards: 

-   Heading syntax (so far, I've seen unanimous support for hash syntax)
-   Line length -- 80 character limit? No limit, and people use text wrapping within their editor? 
-   Ordered list coded as `1. 2. 3.` or coded as `1. 1. 1.`? 
-   Etc. 

To reiterate, please voice your opinion here, "yes" or "no" along with any strong feelings or further clarification. 

@totten @joannechester @michaelmcandrew @nganivet  tagged because you have all been somewhat involved in this question as it has emerged, including [here](https://github.com/civicrm/civicrm-dev-docs/pull/20). Please tag others who you think might care about this topic.

**Comment by seanmadsen** [comment]
I lean slightly towards "yes", but I don't really care too much. 

Note: originally I incorporated some markdown standards into [edits](https://github.com/civicrm/civicrm-dev-docs/commit/6b6f47c05b765df565e9b4ce8890492d7c622cff) I made to the Dev Guide, but later [removed](https://github.com/civicrm/civicrm-dev-docs/commit/1c325a2cc77671458fa959e52ee677d7868bce0b) the language about these standards because I learned that the code in the User Guide (on which I based the standards) is using syntax consistent with a [migration tool](http://pandoc.org/installing.html) and not consistent with intentional decisions made by team members.

**Comment by michaelmcandrew** [comment]
Yes, but only for the things we really care about.

**Comment by nganivet** [comment]
Yes, but make it a suggestion rather than a mandate (ie. weak standards).

**Comment by totten** [comment]
Overall, soft no on "standard". The space for variation in Markdown isn't that big, and different tools impose different preferences. But that's a soft opinion. Posting some suggestions seems OK.

Possible protocol: when a newcomer proposes a patch, try to focus your feedback on the merit of the writing and refrain from feedback on the choice of Markdown notations. However, if the formatting makes a lot of deviations from the suggestions, then give a one-sentence tip with a hyperlink to the suggestions.

In terms of what to suggest/standardize... my feelings vary a bit depending on the element:

 * Line-wrapping and ordered lists -- There may be functional value in standardizing these because they affect many lines at a time -- and that sometimes affect merges.
 * Headings and unordered lists -- Maybe there's some aesthetic value in standardizing these.
 * Bold and italics -- Don't see much upside in standardizing these.

**Comment by michaelmcandrew** [comment]
[appreciate that i might be hijacking this thread somewhat and talking about a style guide, but it seems relevant...]

> the User Guide (on which I based the standards) is using syntax consistent with a migration tool instead of syntax consistent with intentional decisions made by team members.

... is not completely correct.

In the user guide, we don't have markdown code standards so much as formatting standards, which are aimed at making the documentation as readable and consumable (mobile, epub, pdf) as possible.

For example:
* use a max of 3 heading levels
* always start a chapter with an h1
* use bold to refer to UI elements

These standards grew organically out of the documentation process and were useful and necessary to ensure consistency for the end user. I suspect similar conventions will appear as the developer docs grow.

https://github.com/civicrm/civicrm-dev-docs/blob/master/docs/markdownrules.md has a few of these though they aren't necessarily framed in terms of the *why*. I'd suggest that as time goes on, if developer documentation writers uncover some good practice, it makes sense to document them here, along with they why.

also ...
> different tools impose different preferences

...but some don't, while others have configurable options, so it makes sense to state a preference.

One approach would be to add tips and requirements to the standards / style guide as they are uncovered...

**Comment by seanmadsen** [comment]
Good thoughts @michaelmcandrew . As it happens, I was in the process of [proposing some content standards](https://github.com/civicrm/civicrm-dev-docs/pull/26) as you were writing the above comment.

For clarification: 
-   "Markdown standards" specify how to choose between several markdown syntax options that all produce the same HTML
-   "Content standards" specify how to write things that actually produce different results to the human *reader* of the documentation

Perhaps we can continue the discussion of *content standards* in that PR? And keep this issue for *markdown standards*?

**Comment by totten** [comment]
Good call @michaelmcandrew. +1 for content standards.

**Comment by ErichBSchulz** [comment]
+1 for standards

Line wrapping especially to allow for smaller diffs

Also worth asking contributors to separate formatting and content changes
into separate patches.

**Comment by seanmadsen** [comment]
Ok I'm closing this issue now with the conclusion that we have a rough consensus around: **Yes -- include *some* markdown code standards**. 

Will create separate issue to facilitate group decision on the content of such markdown code standards.
