### ISSUE TITLE
Re-organize content about XML menu tags

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#242]
There's some good content on the [hook_civicrm_xmlMenu](https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_xmlMenu/) page about the XML structure of the routing/menu system. 

It would be nice to: 

1. Create a new page for this content alongside [framework/schema-definition/](https://docs.civicrm.org/dev/en/latest/framework/schema-definition/)
1. Re-organize the content to be formatting more like the schema definition content
1. Edit the hook page to remove the content and link to the newly-organized content

Tim [agrees](https://github.com/civicrm/civicrm-dev-docs/pull/227#issuecomment-319467179).

**Comment by seamuslee001** [comment]
See also https://github.com/civicrm/civicrm-dev-docs/pull/394
