### ISSUE TITLE
Organize "Framework => Database" section

### ISSUE THREAD

**Issue by totten** [civicrm/civicrm-dev-docs#256]
The current page "Framework => Schema definition" is labeled/positioned in a somewhat confusing way -- it talks specifically about "the XML schema for generating the database schema", but it doesn't talk about any *other* XML schemas, and it doesn't discuss the actual database schema. 

This ambiguity could be clarified by organizing a full section for the "Database", eg

 * __Framework__
   * __Database__
     * __Overview__ (or __Architecture__ or __Scripts__) -- Talk about `GenCode`, `bin/setup.sh`, `bin/regen.sh`, `xml/templates`, and `sql/civicrm*.mysql`
     * __ERD__ (or __Schema__ or __Design__) -- Talk about ways to learn/investigate the schema
     * __XML__ -- talk about the XML file format used by GenCode

**Comment by seanmadsen** [comment]
Existing content to migrate to ERD page: https://civicrm.stackexchange.com/questions/19704/er-diagram-for-the-latest-civicrm-foreign-key-in-structure-test-cases-plans/19706#19706

**Comment by seamuslee001** [comment]
@seanmadsen i think this can be closed now or do you want to keep it open until we do the Tools documentation?

**Comment by seanmadsen** [comment]
Nah. Closing
