### ISSUE TITLE
Incorporate Documentation on IDS in Security Docs

### ISSUE THREAD

**Issue by seamuslee001** [civicrm/civicrm-dev-docs#281]
@totten @seanmadsen i was thinking that for a 2nd pass after the Security Docs PR is merged, we should look at including the IDS system in someway as it is a security feature unless its already covered and i didn't see it. I think it would be useful to have more documentation on it.

**Comment by totten** [comment]
That's a good idea.

FWIW, the only text that I'm aware of covering PHPIDS is this:
 * https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_xmlMenu/#xml-ids
 * https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_alterMenu/

That's quite specific to the perspective of "how do I create a new page". I think there's a gap/opening for the question "why does PHPIDS exist, and how does it work?"
