### ISSUE TITLE
Simplify naming/nomenclature for extensions

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-dev-docs#31]
I'm not sure if a conscious decision has been made in this regard already, but I'm bringing it up now as it seems like the right time. In the developer documentation on the wiki, there have been a few different types of extensions defined. See the child pages of https://wiki.civicrm.org/confluence/display/CRMDOC46/Create+an+Extension.

They include:

1. Module Extension
2. Custom-Search Extension
3. Payment-Processor Extension
4. Report-Template Extension

My understanding is that 2-4 are deprecated ways to make an extension and that they are rarely (if ever) used.

If we stopped mentioning them, it would mean we didn't have to use the term 'module extension' either and we could just call all extensions extensions.

I'm aware that I might be missing some of the nuances of the history of extension naming (and maybe this has been agreed upon informally already) but think it would be great if we were able to simplify the terminology and this sounds like a good time to do it.

**Comment by ErichBSchulz** [comment]
Michael just noting I was getting ready to port this page to mkbooks 

and its new home is: https://github.com/civicrm/civicrm-dev-docs/blob/master/docs/extensions/basics.md

**Comment by ErichBSchulz** [comment]
would be awesome to delete any deprecated stuff before I start work on moving the sub page

Note Seans plans for the [existing wiki pages](https://docs.google.com/spreadsheets/d/1ZPq34FuYLBhEzXM2iEGYVZUFLbVZ2CpA3BknLpeHqCQ/edit#gid=0) and [the new structure](https://docs.google.com/spreadsheets/d/1ZPq34FuYLBhEzXM2iEGYVZUFLbVZ2CpA3BknLpeHqCQ/edit#gid=81426795) which is what I was working on

**Comment by seanmadsen** [comment]
The new structure I proposed is based pretty strongly on *the content in the wiki* and only very weakly on *actual knowledge about current development practices* (because I'm still learning). I enthusiastically support deviations from my proposed structure that better represent the most up-to-date info! If this means we axe pages like "Custom search extension" etc and stop using the language "*Module* extension", I'm all for it!

**Comment by totten** [comment]
+1 for only discussing `module` extensions in the updated doc.

Regarding `search`, `payment`, and `report` ... we kept those pages in the wiki for a long time as reference material for people on old versions. However, I suppose it's ok to delete them now -- the old material should still available in `CRMDOC46`, `CRMDOC45`, etal.

**Comment by GinkgoFJG** [comment]
I second Tim. At most I would mention that there used to be other types and that they are deprecated 
(Tim, should we strike them from civix altogether?!) and if you really need to know about them here are links to legacy docs but you should always write run-on sentences and never use punctuation.

**Comment by totten** [comment]
@GinkgoFJG I'm pretty sure we've already removed the `civix` options for `report` and `search` extensions. The help text for `generate:report` and `generate:search` say that they're for `module` extensions.

@michaelmcandrew @ErichBSchulz @seanmadsen In the gdoc's tab for "wiki-pages", it looks like we don't list the  `search`/`payment`/`report` docs, which seems good. Is there any other action that's needed to close this?

**Comment by ErichBSchulz** [comment]
maybe deleting the deprecated pages off the 4.7 branch of the wiki - or failing that sticking a bit fat `deprecated` banner on them?

**Comment by seanmadsen** [comment]
I agree. Going forward, extensions documentation (in Dev Docs) will no longer talk about `search`/`payment`/`report`. 

Closing.
