### ISSUE TITLE
Import "Mailer Settings" wiki page

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#313]
This wiki page https://wiki.civicrm.org/confluence/display/CRMDOC/CiviMail+Mailer+Settings

is referenced here: https://docs.civicrm.org/dev/en/latest/framework/civimail/#inbound-civimail-events

would be good to import that wiki content

**Comment by seamuslee001** [comment]
@seanmadsen is the only thing left on here to update the URL to point to the information in the sysadmin guide?

**Comment by seanmadsen** [comment]
Ahhh. This issue can actually be closed now. I created it before the Sysadmin Guide project. Now that the content is migrated to the Sysadmin Guide, we're all set.
