### ISSUE TITLE
Import "Override CiviCRM Settings" wiki page

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#314]
This wiki page: https://wiki.civicrm.org/confluence/display/CRMDOC/Override+CiviCRM+Settings

is referenced here: https://docs.civicrm.org/dev/en/latest/framework/setting/#what-is-a-setting

would be good to bring in that content (or remove the link, if the content is not useful).

**Comment by seamuslee001** [comment]
Closing this as PR to update link to relevant documenation in sysadmin guide has been done
