### ISSUE TITLE
Re-organize docs on tokens

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#316]
We have this page in the Dev Guide: https://docs.civicrm.org/dev/en/latest/framework/civimail/tokens/

but I kind of think it belongs in the *User Guide* here: https://docs.civicrm.org/user/en/latest/email/using-tokens-in-emails/

Anyone else want to weigh in?

**Comment by MegaphoneJon** [comment]
That makes sense to me.  It should be its own page though - "Token Reference".  In fact, I've commonly seen user guides that would put this in an appendix.

I also think it's remiss not to mention Fancy Tokens in the checksum section.

**Comment by totten** [comment]
Agree. Documentation with the list of tokens belongs in the User Guide.  Documentation about coding-conventions/development of tokens belongs in the Dev Guide.
