### ISSUE TITLE
Document new procedures for safe migration from production to non-production instances

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#322]
Here is a change to core that should be documented: 

* https://github.com/civicrm/civicrm-core/pull/8724
* https://issues.civicrm.org/jira/browse/CRM-18231

**Comment by seanmadsen** [comment]
On looking deeper into this, I think the new docs probably belong in the (to-be-created) System Administrator Guide. For now we could either put this new content in the wiki or the Dev Guide and move it to the Sysadmin Guide once it's created.

**Comment by MegaphoneJon** [comment]
I think this is more appropriate for the sysadmin guide.  Thoughts @seanmadsen?

**Comment by MegaphoneJon** [comment]
I was just reading the source code to create docs when I found this: https://docs.civicrm.org/sysadmin/en/latest/misc/staging-production/.

This page is pretty inaccurate - which I believe Tim referenced on the PR - so I'll continue my work and close this ticket with that PR.

**Comment by seanmadsen** [comment]
Yep. Agreed. Now closing in favor of https://github.com/civicrm/civicrm-sysadmin-guide/issues/63
