### ISSUE TITLE
How to redirect from wiki/CRM to Dev Guide

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#35]
@totten I really like how you [created](https://issues.civicrm.org/jira/browse/INFRA-230) a way for us to redirect from wiki/CRMDOC to the Dev Guide. 

But now I need a way to redirect from wiki/*CRM* to the Dev Guide. Specifically, I'd like to redirect https://wiki.civicrm.org/confluence/display/CRM/Book+style+guide to `docs/best-practices/documentation-style-guide.md`

How can I do this?

**Comment by seanmadsen** [comment]
Related: #26

**Comment by totten** [comment]
@seanmadsen , I added `redirects/wiki-crm.txt` (0c6ce37bbf02ebb88d2f4062ca6639fae64369a1) and updated the Confluence webserver to load that.
