### ISSUE TITLE
Buildkit install docs assume `/etc/apache2/conf.d`

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/civicrm-dev-docs#374]
My Apache knowledge is not up to date, but I believe there are some distros which don't use this directory. I've seen `/etc/httpd` and I've also seen `/etc/apache2/conf-{available,enabled}`.

In [this ~dev-newcomers](https://chat.civicrm.org/civicrm/pl/oz8k5tip3f8z5qskucbhgjpane) chat, @hassan3152 followed instructions accurately but the results were unsuccessful.

The instructions [as per current](https://github.com/civicrm/civicrm-dev-docs/blob/7034a0df604e77cc9342b5bd164391ae8d7491f8/docs/tools/buildkit.md) are really good, but not helpful for someone with an Apache layout not matching the docs.

I'm not sure how best to rephrase this.

We probably can't try to handle *all* possibilities (`/usr/local/etc/{httpd,apache2}`, `/opt/local/apache2/conf/`, ...). But we can tell people to find the right directory first?

**Comment by seamuslee001** [comment]
@xurizaemon good point. I think Centos is one of those distros and maybe that Linux family.

**Comment by totten** [comment]
This is why `amp config` does a scan and suggests a particular file...
