### ISSUE TITLE
Migrate testing content from Testapalooza

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#389]
Good content here from @totten that should probably be migrated into the Dev Guide: 

https://github.com/civicrm/org.civicrm.testapalooza/blob/master/civi-test.md

**Comment by seanmadsen** [comment]
Hey @totten I just noticed there is still a bunch of content here: https://github.com/civicrm/org.civicrm.testapalooza/blob/master/civi-test.md

Want to delete that and replace it with text that directs readers to https://docs.civicrm.org/dev/en/latest/testing/phpunit/ ?

I noticed this because I happened to run `civix generate:test` and read the comments in the file which directed me to testapalooza.

**Comment by seanmadsen** [comment]
Actually, what is the function of the Testapalooza project anyway? Is it still relevant? Can we just move *all* of that content into the Dev Guide?

**Comment by totten** [comment]
> Actually, what is the function of the Testapalooza project anyway? 

Testapalooza was an initiative to re-design the test system -- to make it less of a framework/monolith (hard-wired into civicrm-core) and more of a utility/library (that can be incorporated into other projects). It produced a git repo (with docs/examples) and several utilities (`cv`, `CiviTestListener`, `Civi\Test`).

> Can we just move all of that content into the Dev Guide?

I think most of it has been -- either in `testing/index.md` or `testing/phpunit.md`.

Maybe what you're really saying is, "Let's delete the old version"? I'm not so eager on that. 

*Analytically*, most of the substance has been reproduced. But there's still *something* that doesn't come through. As if... the Dev Guide were written at a 9th-grade reading-level, and the Testapalooza docs were written at a 12th-grade reading-level.? Or as if... the audience or perspective is different? Or maybe it's my own sentamentalilty? Or maybe it's a fear that bits of information will be removed from the Dev Guide -- and I like having Testapalooza docs as a fallback (b/c they're less filtered -- they map closer to how I really think about the problem-space). Whatever it is, I can't quite put my finger on it.

The best analogy I can think of... we often publish blogs when some milestone is reached. We don't delete the blogs when technical details change. However, this doesn't preclude us from keeping "living documentation" about the most common use-cases/perspectives.
