### ISSUE TITLE
more navbar scroll improvements

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-dev-docs#41]
@sean - awesome work on https://github.com/civicrm/civicrm-dev-docs/pull/39 :)

a couple of thoughts:

1) this works for inline elements, but doesn't seem to work for example, for https://docs.civicrm.org/dev/en/master/extend-stages/ (when viewed on a small screen.

2) is there an easy way to reference an external js file so that we can duplicate these improvements across our books? Maybe by referencing a custom theme (that we could store in civicrm-docs) with the extra js, etc.

**Comment by seanmadsen** [comment]
I'm closing this issue because

- point 1 was addressed in #42 
- point 2 can be addressed in [civicrm-docs/#9](https://github.com/civicrm/civicrm-docs/issues/9)
