### ISSUE TITLE
Add documentation for the hook_civicrm_generateIdentifier (CRM-21289)

### ISSUE THREAD

**Issue by kainuk** [civicrm/civicrm-dev-docs#422]
This hook is not yet part of CiviCRM but a PR is submitted. Add the documentation when the pull request is accepted. (https://github.com/civicrm/civicrm-core/pull/11110).

**Comment by seanmadsen** [comment]
Since we have an open PR for this fix (#423) I'm closing this ticket. Unlike CiviCRM core, we don't need to have a ticket to correspond to every PR.
