### ISSUE TITLE
Poll: What standards do we want to promote for markdown code?

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#43]
What standards do we want to promote for markdown code?

In issue #24, most people supported gently recommending *some* markdown code standards to be upheld in the writing of documentation guides in mkdocs. This issue is to help us decide *what* goes in these standards. **Please vote by adding a comment** with your choices on the following questions, and I will do my best to facilitate a decision that satisfies everyone. 

**Line length:**

- Option 0: No standard
- Option 1: Hard-wrapping at 80 characters (when possible)
- Option 2: Each paragraph or list-item is kept on its own line
- Option 3: Each sentence is kept on its own line (with single line breaks between sentences within the same paragraph).

**Ordered lists:**

- Option 0: No standard
- Option 1: Use `1.` for all list items
- Option 2: Use `1.`, then `2.`, then `3.`, etc.

**Unordered lists:**

- Option 0: No standard
- Option 1: Use `-` to delimit list items
- Option 2: Use `*` to delimit list items

**List spacing:**

- Option 0: No standard
- Option 1: Clean spacing, by starting list item content 4 characters in to align with nested lists. (e.g. unordered item is: *dash* (or asterisk), then *three spaces*, then *content*.)
- Option 2: Simple spacing by using the delimiter, then one space, then content

**Headings:**

- Option 0: No standard
- Option 1: Use hash syntax for headings

**Location:**

- Option 1: Have a dedicated (but small) page for markdown code standards
- Option 2: Integrate markdown code standards into the page on [markdown syntax](https://docs.civicrm.org/dev/en/master/markdownrules/)
- Option 3: Integrate markdown code standards into the (up and coming) [Style Guide](https://github.com/civicrm/civicrm-dev-docs/pull/26)

A **sample ballot** for you to copy-paste-edit:

```
- Line length: 2
- Ordered lists: 0
- Unordered lists: anything but 2
- List spacing: 0
- Headings: 1
- Location: don't care
```

**Comment by seanmadsen** [comment]
My vote: 

- Line length: 2 or 3, but open to 1
- Ordered lists: 0 or 1
- Unordered lists: 0 or 1
- List spacing: 1
- Headings: 1
- Location: don't care

**Comment by nganivet** [comment]
Line length: 2
    Ordered lists: 1
    Unordered lists: 1 or 2
    List spacing: 0
    Headings: 1
    Location: 3 and move markdown syntax page within this guide

**Comment by totten** [comment]
* Line length: Don't care
 * Ordered lists: Don't care
 * Unordered lists: 2
 * List spacing: ... the normal spacing (indent the `*` as necessary; then one space; then text)
 * Headings: 1
 * Location: Don't care

**Comment by michaelmcandrew** [comment]
- Line length: 0
- Ordered lists: 2
- Unordered lists: 2
- List spacing: 0
- Headings: 1
- Location: not sure :)

**Comment by seanmadsen** [comment]
Ok I'd like to close this poll now and write some markdown standards that *recommend* (but not require) content editors to use the following standards: 

* Line length: 2 - Each paragraph or list-item is kept on its own line
* Ordered lists: 1 - Use `1.` for all list items
* Unordered lists: 2 - Use `*` to delimit list items
* ~List spacing: 0~ i.e. no standard (just mentioned here for completeness)
* Headings: 1 - hash syntax
* Location: 2 - store in the markdown syntax page

This proposal doesn't satisfy everyone perfectly, but it does seem like the center of mass (so to speak) of everyone's opinions. It means @michaelmcandrew would sacrifice "ordered lists", @nganivet would sacrifice "location", and @seanmadsen would sacrifice "unordered lists". These are the only cases where a standard would be in place that would go against a person's opinion. 

@nganivet to say a bit more about location: I don't want to combine the [markdown](https://docs.civicrm.org/dev/en/master/markdownrules/) page with the [style guide](https://docs.civicrm.org/dev/en/master/best-practices/documentation-style-guide/) because (a) they're both pretty big pages that each already have deep heading structures (i.e. lots of level 3 headings), and (b) a conceptual distinction between them is relatively intuitive. I think the markdown standards are too small to warrant a separate page, and they fit better within the markdown page than the style guide page. Plus everyone else said they don't care about this one. So that's why I picked option 2 in the end.

Also, Erich told me he didn't want to vote -- he just wanted to see *some* standards. 

I'm going to leave this issue open for a couple more days. Then if we don't get any final concerns, I'll publish the markdown standards described above.

**Comment by totten** [comment]
Thank you, @seanmadsen.

**Comment by ErichBSchulz** [comment]
hehe - too late for me to vote 1 on line-length then?

I think good to be consistent with coding standards... and it make for better diffs when reviewing changes

(no dramas - just putting it out there!)

**Comment by seanmadsen** [comment]
Ok, so on the line length issue we have: 

| person | 0 - no standard | 1 - hard wrap | 2 - long lines |
| -- | :--: | :--: | :--: |
| @seanmadsen |  | *open to it* | ✔ |
| @nganivet |  |  | ✔ |
| @totten | - | - | - |
| @michaelmcandrew | ✔ |  |  |
| @ErichBSchulz |  | ✔ |  | 

Hmmm.... Going by plurality option 2 still wins, but only by a small margin. It would be nice to have more of a consensus. Anyone else want to weigh in? @totten ? @GinkgoFJG ? @joannechester ?

**Comment by nganivet** [comment]
do the standard markdown editors automatically break lines at 80? If not, then I would stick with my vote as I do not want to put the burden of counting chars/breaking lines on the users. If they all do, they you can move my vote to 'don't care'.

**Comment by seanmadsen** [comment]
Good question @nganivet. I just did a quick survey of the most popular web-based markdown editors: 

| editor | hard wrap | soft wrap (makes long lines) | no wrap |
| -- | :--: | :--: | :--: |
| GitHub "edit file" | ✘ | **default** | *optional* | 
| [GitHub JBT](https://jbt.github.io) | ✘ | ✔ | ✘ |
| [Dillinger](http://dillinger.io/) | ✘ | ✔ | ✘ |
| [Stack Edit](https://stackedit.io) | ✘ | ✔ | ✘ |
| [simplemde](https://simplemde.com/) | ✘ | ✔ | ✘ |
| [vuejs](https://vuejs.org) | ✘ | ✔ | ✘ |

@ErichBSchulz does this sway you towards option 2 at all?

**Comment by seanmadsen** [comment]
This is interesting: I just happened to notice [this commit](https://github.com/civicrm/civicrm-core/commit/2b95de3951916b7178052a1e77924bc7593148ea) where @agh1 changed a markdown file from `option 2 - long lines` to `option 1 - hard wrap`.

**Comment by ErichBSchulz** [comment]
heh - listen I'm a big fan of the 80 char wrap - but its really not a big deal

I have 2 key macros in vim that will change from one to the other

my sense is that dev doc authors should really be using an editor that supports drupal (ie civicrm) coding standards so that is my rationale - but happy to go with flow!

**Comment by seanmadsen** [comment]
Ok, in an effort to move things along, I'm closing this issue now with the following outcome...

Make standards that *recommend* (but not require) content editors to use the following standards: 

* Line length: 2 - Each paragraph or list-item is kept on its own line
* Ordered lists: 1 - Use `1.` for all list items
* Unordered lists: 2 - Use `*` to delimit list items
* Headings: 1 - hash syntax
* Location: 2 - store in the markdown syntax page
