### ISSUE TITLE
Add to style guide: avoid dogma

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#50]
I'm not sure how best to describe this sentiment, but @michaelmcandrew had a good piece of feedback for some of my writing in [this comment](https://github.com/civicrm/civicrm-dev-docs/pull/45#issuecomment-271791737). 

> We tried to avoid too many constructions that tell people what they should/have to do. Or that there is one way to approach being a developer. Preferring constructions that suggest ways that people can do things. Since we were concerned to avoid things getting proscriptive or feeling intimidating from a user perspective, and we like having a guide that can be consumed by people in different ways.

I like this concept, and I think it would make a great addition to the Style Guide (after it's [merged](https://github.com/civicrm/civicrm-dev-docs/pull/26)). @michaelmcandrew would you want to write up a short point about this? Or maybe we could just use the above text?

**Comment by michaelmcandrew** [comment]
I think the above text is good for now and we can improve it as we go :)

**Comment by seanmadsen** [comment]
closing, as this is now contained within PR #26
