### ISSUE TITLE
How to store hooks documentation

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#52]
## Problem description

Most of the content migration from the wiki is pretty straightforward (import/re-organize/clean). But the [hooks documentation](https://wiki.civicrm.org/confluence/display/CRMDOC/Hook+Reference) stands out to me as having far more pattern-like content than any thing else slated for migration. As such, I think it's worth doing at least a small amount of structural planning before we begin to bring over this content.

## Representative examples, from current documentation

To get your head into this problem, check out the following example cases of hooks documentation pages, which I selected to represent a good range of characteristics in the existing documentation.

- [hook_civicrm_merge](https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_merge) - a good prototypical case of the documentation page being complete and concise
- [hook_civicrm_trigger_info](https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_trigger_info) - lacking structure
- [hook_civicrm_alterSettingsMetaData](https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_alterSettingsMetaData) - almost empty
- [hook_civicrm_buildForm](https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_buildForm) - really long "example" section
- [hook_civicrm_customFieldOptions](https://wiki.civicrm.org/confluence/pages/viewpage.action?pageId=86213400) - this one is deprecated
- [hook_civicrm_xmlMenu](https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_xmlMenu) - has a "comparison of related hooks" section (rare)
- [hook_civicrm_apiWrappers](https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_apiWrappers) - non-standard sections

## Observed patterns in the existing documentation

Documentation for one hook can have the following *sections*:

- Description
- Deprecation (rare)
- Related hooks (rare)
- Definition
- Parameters (sometimes complex)
- Returns
- Availability (missing in most cases)
- Examples (sometimes very long)

Hooks are also categorized into: Batch, Case, CiviRules, Database, Entity Hooks, Extension lifecycle, Form, GUI, Mail, Permission, Profile Hooks, Report Hooks, Uncategorized

## Possible solutions for a structure to adopt, going forward

*Note that some of these options have "sub-options", so you can have "Option 1, with H4, with js" or variations thereof.*

### Option 1 - one giant page, categorized

`https://docs.civicrm.org/dev/en/latest/hooks#hook_civicrm_merge`

- All hooks on one page
- H2 used for hooks *categories* (which show up in navigation menu when reading the hooks page)
- H3 used for each hook, by name (which does *not* show up in navigation menu)
- Sub-option H4
    - **"With H4"** the *sections* for each hook would be level H4. The text within the section would be paragraph. *Concern: getting pretty deep with the heading levels.*
    - **"Without H4"** the sections for each hook would be unordered list items.
- Sub-option js
    - **"with js"** we could build some js into the site theme to make the *sections* for each hook collapsible (this way a long example doesn't eat up screen space). Potentially the entire hook could be collapsible, so that when you first view the page you just get a large list of all hooks. *Concern: implementation time/feasibility*
    - **"without js"** the page would be very very long. *Concern: potentially a somewhat cumbersome user experience.*
- *Concerns:*
    - *Unless we choose **js**, it's hard for the user to see a list of all the available hooks*
    - *With each hook as H3, there is no easy way for a reader to obtain a hyperlink that points to one hook*
    - *No easy way to hyperlink to a section within a hook*

### Option 2 - one giant page, alphabetical

`https://docs.civicrm.org/dev/en/latest/hooks#hook_civicrm_merge`

- All hooks on one page
- H2 used for hooks (which show up in navigation menu when reading the hooks page)
    - Reader can use navigation menu to obtain a hyperlink that points to one hook
- no more categorization
- H3 use for hooks *sections*
- Sub-option **"js"** *(described in option 1)*
- *Concerns:*
    - *No more categorization (a significant regression for readers, potentially)*
    - *No easy way to link to a section within a hook*

### Option 3 - one page per *category*

`https://docs.civicrm.org/dev/en/latest/hooks/database#hook_civicrm_merge`

- Each hook *category* has its own markdown file
- H2 used for hook name (which show up in navigation menu when reading the category page)
- H3 use for hooks *sections*
- Sub-option macro
    - **"with macro"** some system would exist (perhaps manual at first, and then auto-generated) to compile hook information into one page that lists all hooks in an index page
    - **"without macro"** no master list of all hooks would be visible anywhere 
- Sub-option expanding-menu
    - **"With expanding-menu"**: The entire site's navigation menu would be expanding, as discussed in #54 . (Note that *headings* expand too, so you can click on H3 in the menu)
    - **"Without expanding-menu"**: The site's navigation menu would stay the same as it is now -- fully expanded, and non-interactive
- Sub-option permalink
    - **"With permalink"**: The theme includes functionality to hover over a heading (of any level) and obtain a URL that links to that heading.
    - **"Without permalink"**: The site would be have as it does now and only provide URLs that link to H2 headings within the nav menu
- *Concerns*
    - *Unless we use expanding-menu, there is no way to see a list of all hooks at once*
    - *Unless we use expanding-menu, there is no easy way to link to a section within a hook*

### Option 4 - one page per hook

`https://docs.civicrm.org/dev/en/latest/hooks/database/hook_civicrm_merge#parameters`

- Each hook has its own markdown file
- H1 is used for hook name
- H2 is used for hook *sections*
- The navigation menu is structured to convey hooks categories
- Sub-option deep-nav
    - **"With deep-nav"**: One folder for hooks. Folders within that for categories. Each hook belongs within one and only one category.
    - **"Without deep-nav"**: Folders for hooks categories put into top-level navigation structure.
- Sub-option **"expanding-menu"** *(described in option 3)*
- *Concerns:*
    - *Without expanding-menu, the navigation menu is really huge. Anything positioned below hooks might get lost to the reader*

### Option 5 - a separate book for hooks

`https://docs.civicrm.org/hooks/en/latest/database/hook_civicrm_merge#parameters`

- Still use MkDocs, but have a dedicated book for them, separate from the Dev Guide
- Each hook has its own markdown file
- H1 is used for hook name
- H2 is used for hook *sections*
- The navigation menu is structured to convey hooks categories
- Concerns: 
    - *Too many books?*

### Option 99 - don't use mkdocs

`https://hooks.civicrm.org/hook_civicrm_merge#parameters`

- I think it's worth considering whether mkdocs is really even the best platform to store this kind of more-structured content.
- There could be an entirely separate documentation site at docs.civicrm/hooks or hooks.civicrm.org
- From the reader's perspective, the API reference documentation already exists, to a large extent, outside the Developer Guide (in the API explorer), which I think is reasonable precedent for having a separate tool that covers hooks documentation.
- Not sure what this separate tool would look like, but I figured it'd be worth pondering.
- *Concerns:*
    - *Confusion to readers in having so many separate documentation systems*
    - *Implementation time/feasibility/maintainability*

## YOUR INPUT NEEDED!!

Ok now that you've read all this, I want to hear what you think!

In your comments:

- You can say things like `I want Option 1, without H4, with js`.
- You can also add concerns, and I'll edit this issue to post them alongside mine up here.
- You can add new options or sub-options and I'll post them up here.

**Comment by seanmadsen** [comment]
Personally I like `Option 1, with H4, with js` or `Option 3, with deep-nav`, or maybe even `Option 4`

**Comment by ErichBSchulz** [comment]
great question! 

I thinks we need option 5 using the current wiki categories for each page:

```
Database hooks
Extension lifecycle hooks
Form hooks
GUI hooks
Mail hooks
Permission hooks
Uncategorized hooks
Case hooks
Batch hooks
Entity Hooks
CiviRules hooks
Profile Hooks
Report Hooks
```

I think from this structure maybe we can make some kind of macro that auto generates an alphabetic index page by `grep`ping and `sed`ing the category pages??? (could be semi-automatic to start)

the benefit of one page per topic is it probably make a reasonable page length and allows a little overview?

**Comment by nganivet** [comment]
+1 on the above, one page will be too long, we need to have a ToC listing categories (linking to individual pages) and hooks inside each category (linking to anchors in the category pages). The wiki used to do that automagically, but we might have to custom code the creation of this ToC now.

<rant>One thing that is mostly missing from the current documentation is a precise and/or accurate definition of the input parameters to the hook, and the expected outputs. For example on the hook_civicrm_pre page, it says we are receiving an object but not what is inside. For the contact object, are the related information (ie. phone, address, ...) included or not? Are the custom fields included? This has changed significantly over the past major releases, so documenting it (and having the necessary QA tests to ensure this is accurate) would be worthwhile.</rant>

**Comment by michaelmcandrew** [comment]
Yes - an interesting and tricky problem :)

Ansible have faced a similar (bigger?) documentation problem for their modules. I'm not sure how it is implemented, but it works quite nicely: http://docs.ansible.com/ansible/modules_by_category.html. It isn't perfect (hook name does not appear in the menu) but it works OK.

After spending a few mins thinking about it, I think out of the mkdocs solutions, a one page per hook is the least troublesome from the perspective of creating URLs e.g. docs.civicrm.org/dev/hooks/hook_civicrm_install#parameters. 

I'm personally not too keen on one page per topic - it makes it harder to link to a hook section. e.g. you can link to hooks/extension-lifestyle#hook_civicrm_install, but how do you link to the parameters section within that. But there might be ways to automate around that.

Did we rule out using doc subdirectories? like docs.civicrm.org/dev/hooks/lifecycle/hook_civicrm_install#parameters :worried: 

Definitley not against a seperate system for hook reference (like drupal does: https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_css_alter/7.x). I think some markdown based static site generators allow you to defined markdown templates. We could always start with a low tech markdown solution / keep it on the wiki for now and migrate when we decide on a better format.

**Comment by seanmadsen** [comment]
Update: **New idea** a sub-option **"expanding-menu"** (described above) alleviates many concerns! More talk about feasibility in #54

**Comment by totten** [comment]
My first instinct -- motivated by "do something straightforward which is better than status quo" -- is to go with "option 3 - one page per category". 

However, I can be talked out of that...

It's an interesting exercise to compare the APIv3 docs with the hooks. There's several parallels:
 * There's a large number of interfaces.
 * The reader wants to know lots of details about every field and use-case.
 * The details are subject to some amount of change from version-to-version (hopefully not often, and hopefully *backward compatible* change).
 * Mostly, these things are defined in core. However, as we continue to rely on extensions for growth/change, these things are liable to evolve.
 * The early implementations tried to follow a clever design (leveraging `BAO::create()`, `hook_civicrm_buildForm`, etc) that exposed lots of functionality with no thought to quality-control. (Although APIv3 has improved that a lot over the years with better test coverage.)

The current solution for APIv3 is obviously much more mature than for hooks. At the risk of being pedantic, let's recap the APIv3 situation:
 * The devdocs describe general-design/common-patterns about the API -- e.g. the different bindings, the common actions, the common parameters. These docs are closest to Option 3 -- page per category.
 * The API Explorer provides most of the field-level documentation in-app. They're always up-to-date. These docs are closest to Option 99.
 * There are technical/structural safe-guards -- e.g. the same metadata powers the API explorer, the validation logic, and the SyntaxConformanceTest. This isn't perfect, but (borrowing [the swiss cheese metaphor](https://en.wikipedia.org/wiki/Swiss_cheese_model)) it's a pretty good slice of cheese.
 * There's a large library of API-specific test cases (layering in some more cheese).

I think the solution here really depends on what kind of time and what type of labor the doc team wants to do:
 * If we want to spend most of the time on *prose*, then go with Option 3 or 4. This is is easier to plan and easier to scale-out to a Swarm of contributors. The only drawback is that it's harder to keep up-to-date.
     * (Between them, I started out leaning toward Option 3 because I think mkdocs will present it better. But on second thought... I really like how Option 4 creates separate files. If we want to restructure later, this should be easier with separate files.)
 * If we want to spend most of the time on *tooling*, then go with Option 99. This is more work, and it's harder to plan or scale-out because it's more subjective (from our current perspective). The main upside is that overall it'll be easier to maintain long-term quality. Steps:
     * Determine a metadata format for the hook definitions. (The docblocks in `CRM_Utils_Hook` are OK... but not great. Doing better would require something very different.)
     * In "API Explorer", add a new section for exploring "Hooks". This should display the metadata.
     * Start filling in more metadata. (This step might be amenable to a Swarm of contributors.)
     * Create a test-suite similar to `api_v3_SyntaxConformanceTest` -- something using the metadata to ensure that real systems actually comply with the contract.

**Comment by seanmadsen** [comment]
Update: We have a new option - `Option 5`  "a separate book for hooks"  (described in-detail along with all the other options in the description at the very top). **What do people think of this option?**

Personally I like `option 5`, but also like `option 4` and `option 3`. Mostly I'd like to decide on *something* here so we don't end up with `option 0` (continuing to use the wiki) for too long. If I don't hear a lot of support for option 5, I'd like to push ahead with option 3 since it has the most support. But maybe option 5 will satisfy everyone? Maybe?? Would love to hear comments from @ErichBSchulz @nganivet @michaelmcandrew @totten

**Comment by nganivet** [comment]
I like option 4 better than option 3, but not by a huge margin.

Option 5 is for me unrelated - we can start in the existing documentation, either with 4 or 3, and then if it gets too voluminous just copy the pages over to another manual. I would therefore vote it down for now but keep it open if needed further down the line.

**Comment by seanmadsen** [comment]
@nganivet thanks for clarifying -- I thought you were more into 3 than 4. Good to know you like 4. I like 4 and so does Michael. 

To respond to your "start in the existing" / "and then if it gets too voluminous" sentiment: 

My vision for migrating the hooks is: 

1. Figure out how we want to store them
1. Do the whole migration in one merge, so that the switch is atomic across the entire collection of hooks docs. 

If we can, I'd like to avoid confusing readers by having some hooks in one place and others elsewhere. For example, right now it's confusing that the Dev Guide has docs for only 9 hooks. I'd also like to get it right the first time, if we can, so that URLs to hooks docs can be preserved. 

I think it's totally possible to do this hooks migration atomically, and personally I'm excited to work on this by doing the following: 

1. create a script to perform the migration, using [webpage2md](https://github.com/seanmadsen/webpage2md)
1. If wiki content issues cause certain content to migrate improperly, address this by either: (a) improving the script, or (b) fixing the wiki content
1. run the script to perform the migration
1. soon thereafter, merge into dev-docs, at which point all wiki hooks pages will redirect to dev-docs

**Comment by totten** [comment]
* Not a fan of Option 5 right now.
 * If devwork isn't a limitation, I'd go for Option 99 and a solution that parallels APIv3 (guide for general principles; explorer for details).
 * If devwork is a limitation, then I'd vote for 3 or 4. (They're basically equal for me, although I now lean toward option 4; if we ever have time for Option 99, I think the migration will be easier using smaller `*.md` files.)

**Comment by totten** [comment]
`webpage2md` sounds like a nice idea to facilitate migration. Atomic hook migration also sounds like a neat idea.

**Comment by ErichBSchulz** [comment]
My view is still the same.

**Comment by seanmadsen** [comment]
I just talked to @ErichBSchulz on Mattermost. He is okay with Option 4 which means we have a rough consensus around it. Yay!

I'm going to close this issue with the following plan: 

* Migrate hooks docs from the wiki into the Dev Guide
* Use one page per hook as described in `option 4` at the top of this issue
* Perform the migration atomically for all hooks at the same time, if possible
