### ISSUE TITLE
Make extension review process compatible with GitLab

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-dev-docs#520]
1. The extension review process described here...

    * https://docs.civicrm.org/dev/en/latest/extensions/publish/#automated-distribution
    * https://docs.civicrm.org/dev/en/latest/extensions/lifecycle/#formal-review

    ...is dependent on Jira. 

1. Jira reads:

    > Issue creation was disabled on March 31st 2018.

These points seem incompatible to me. 

Can we offer an extension review process that doesn't depend on Jira? 

@GinkgoFJG @twomice any thoughts?

**Comment by twomice** [comment]
Good question. I'll raise this with Frank at our next call.

Thanks,
Allen

On Tue, 10 Apr 2018 18:36:14 +0000 (UTC)
Sean Madsen <notifications@github.com> wrote:

> 1. The extension review process described here...
> 
>     *
> https://docs.civicrm.org/dev/en/latest/extensions/publish/#automated-distribution
>     *
> https://docs.civicrm.org/dev/en/latest/extensions/lifecycle/#formal-review
> 
>     ...is dependent on Jira. 
> 
> 1. Jira reads:
> 
>     > Issue creation was disabled on March 31st 2018.
> 
> These points seem incompatible to me. 
> 
> Can we offer an extension review process that don't depend on Jira? 
> 
> @GinkgoFJG @twomice any thoughts? 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/civicrm/civicrm-dev-docs/issues/520


-- 
Joinery: Mission-critical data solutions
Migrate, integrate, report.

Allen Shaw <allen@joineryhq.com>
903-361-7429

**Comment by joemcl** [comment]
Related to #606 . Anything happening with this @twomice ?

**Comment by joemcl** [comment]
So this is 'fixed' with this right? - https://lab.civicrm.org/extensions/extension-review-requests/issues ?

**Comment by twomice** [comment]
@joemcl There's still one reference to JIRA in https://docs.civicrm.org/dev/en/latest/extensions/lifecycle , for which I've submitted PR #687

**Comment by twomice** [comment]
PR #687 is merged now (thanks @MikeyMJCO!). So this is fixed. Apparently I don't have rights to close.

Request to close this ticket @joemcl

**Comment by joemcl** [comment]
thanks @MikeyMJCO and thanks for closing @seamuslee001
