### ISSUE TITLE
For style guide: how to specify file names

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#53]
In PR #26 @ErichBSchulz [mentioned](https://github.com/civicrm/civicrm-dev-docs/pull/26#pullrequestreview-15619427): 

> need to specify formatting for file names... I prefere `filename.php` (ie backtics `` `filename.php` ``) but the wiki is currently ***filename.php*** (ie 3 stars `***filename.php***`)

Sounds like we should **decide** which way to do it in the Dev Guide

**Comment by seanmadsen** [comment]
I like backticks too.

I'll add this to the style guide, unless we get push back from others within this thread

**Comment by totten** [comment]
+1 backticks

For me, it's less about "files" per se and more about distinguishing *machine-readable symbols* (incl files, classes, functions, variables, tables, columns, commands, etc) and *human-friendly labels* (incl menu items, page titles, subsections, field labels, dropdown items, etc). All machine-readable symbols should use backticks/teletype/monospace. Human-friendly labels can use bold/italic/whatever.

**Comment by seanmadsen** [comment]
Excellent distinction @totten
