### ISSUE TITLE
Investigate/evaluate expanding navigation menu/TOC

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#54]
**Whoa check this out!** http://pip.readthedocs.io/en/stable/user_guide/

See how the menu works in that site? I *like* that! 

The example site above has a menu which expands/collapses only the TOC entries (within the current page). I'm actually thinking *broader* than that (possibly) -- so that *folders* could expand and collapse too. Here's an example of [a site that does collapse folders](http://developer.helpmonks.com/) (but there are some things I don't like about the ux here.) 

More info 
- https://github.com/mkdocs/mkdocs/issues/556
- https://github.com/mkdocs/mkdocs/issues/588

Need to look into this further to see how we could get this on our site, and consider what drawbacks it might have.

Things I've learned: 
- "Read The Docs" (aka RTD) means multiple things
    - A website readthedocs.io that hosts documentation built using *either* MkDocs (like we do) **or** Sphinx (a competing tool)
    - A *theme* for MkDocs called "readthedocs" (that we use)
        - does *not* have any collapsing support
        - source files [contained](https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/readthedocs) within the MkDocs repo
    - A *different theme* for Sphinx called "readthedocs" (that we *can't* use because we don't use Sphinx)
        - *has* a collapsible menu (to a certain extent)
        - source files in this [reop](https://github.com/snide/sphinx_rtd_theme)
- [Other themes for MkDocs](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes) exist. Maybe they already have collapsible menus?

**Comment by seanmadsen** [comment]
Maybe this is *crazy* but with an expanding menu, *all* documentation could live within *one* guide -- user, administrator, and developer. I'm certainly not advocating for this now. And won't until we've done more research into expanding menus, because there would certainly be downsides to an all-in-one approach. But I think there are upsides too, and it's an interesting thing to think about. I don't want to encourage too much debate about this idea within this thread -- mostly just adding some food for thought to the topic of expanding menus, and the possibilities that it opens up.

**Comment by seanmadsen** [comment]
With a menu like this, some of the *concerns* listed in various approaches to [storing hooks documentation](https://github.com/civicrm/civicrm-dev-docs/issues/52) could be resolved. For example, "very long menu" is a concern that would be resolved, as well as "no ability to link to H3 anchors".

**Comment by nganivet** [comment]
Against "all-in-one" as these are very different audiences with very different skills and needs.

**Comment by totten** [comment]
Soft +1 for collapsible menus. Suggest time-boxing efforts on that front.

-1 on "all-in-one" page. There's too much content for that it.

FWIW, if you do investigate other themes, the Bootstrap or Bootswatch one might be interesting -- [`civicrm.org` uses Bootstrap](https://github.com/civicrm/civicrm-website-org/tree/master/drupal/sites/all/themes/civicrm_bootstrap), and maybe you could fetch the CSS from there to make the styling match.

**Comment by michaelmcandrew** [comment]
Hey there,

Re: "all in one", slightly tangential, but it would certainly be good to have a "see all documentation" link (or similar) in a documentation theme that we create.

Re: long menus: Different guides have different parts that are long. The user guide is long because of the amount of parts and chapters. It would be nice to be able to account for that in the menu.

I did look at the different themes and thought that the readthedocs was the most suitable out of those that exist at the moment. I don't think it would be too hard to make a civicrm theme that does what we want with menus (and it is on the [todo list](https://github.com/civicrm/civicrm-docs#to-do ), though it is not something I have any immediate plans for.

**Comment by seanmadsen** [comment]
Closing because we have expandable menus with Material theme now
