### ISSUE TITLE
Document "short" and "long" cache services

### ISSUE THREAD

**Issue by MegaphoneJon** [civicrm/civicrm-dev-docs#549]
See https://github.com/civicrm/civicrm-core/pull/12873.

**Comment by eileenmcnaughton** [comment]
@totten this looks like a good place to ask you what the right way is to interact with the new cache changes.

It's a bit unclear to me from the docs(https://docs.civicrm.org/dev/en/latest/framework/cache/) what 


Civi::cache()

maps to - I believe it is the same as the new

Civi::cache('short')

But it's not clear from the docs whether it 
a) maps to ['*memory*', 'SqlGroup', 'ArrayCache']
b) uses the new withArray

- if it doesn't use withArray potentially we should have a new default 
Civi::cache('fast') 

?

**Comment by totten** [comment]
* `Civi::cache('long')` is equivalent to `['*memory*', 'SqlGroup', 'ArrayCache']`
* `Civi::cache('short')` is equivalent to `['*memory*, 'ArrayCache']` (although the codepath for constructing it is more roundabout)
* `Civi::cache()` == `Civi::cache('short')` == `Civi::cache('default')` == `CRM_Utils_Cache::singleton()`
* Neither `short` nor `long` currently uses the `withArray` option, and I agree we should make that more readily available. I think it's an Ambiguous Question about which way to expose it, e.g. different approaches:
    1. Simply update the existing `short` and `long` to set `withArray => TRUE`
    2. Simply update the existing `short` and `long` to set `withArray => 'fast'`
    3. Create a couple variants; defaults carry-on the status-quo (Table A)
    4. Create a couple variants, defaults switch to using optimization (Table B)
    5. Go hog wild with different variants (Table C)
    6. (*Aside*: There is one approach I'd rule out. When first dipping toes in this problem-space, I assumed it'd make sense to expose more advanced settings/preferences for sysadmins. So a sysadmin could toggle the `withArray` option for specific cache. That seems fine for custom/named caches, but for the general-purpose caches -- like `short` and `long` -- I don't think it makes sense. The general-purpose framing means that different dev's can throw random things into it, and eventually a sysadmin could get boxed-in such that no configuration works with all modules.)

__Table A__

| Name | Storage | Thread-Local Optimization |
| --- | --- | --- |
| `short` | `['*memory*',  'ArrayCache']`  | (none) |
| `short+` | `['*memory*',  'ArrayCache']`  | `withArray => 'fast'` |
| `long` | `['*memory*', 'SqlGroup', 'ArrayCache']` | (none) |
| `long+` | `['*memory*', 'SqlGroup', 'ArrayCache']` | `withArray => 'fast'` |

__Table B__

| Name | Storage | Thread-Local Optimization |
| --- | --- | --- |
| `short!` | `['*memory*',  'ArrayCache']`  | (none) |
| `short` | `['*memory*',  'ArrayCache']`  | `withArray => 'fast'` |
| `long!` | `['*memory*', 'SqlGroup', 'ArrayCache']` | (none) |
| `long` | `['*memory*', 'SqlGroup', 'ArrayCache']` | `withArray => 'fast'` |

__Table C__

| Name | Storage | Thread-Local Optimization |
| --- | --- | --- |
| `short` | `['*memory*',  'ArrayCache']`  | (none) |
| `short+` | `['*memory*',  'ArrayCache']`  | `withArray => TRUE` |
| `short++` | `['*memory*',  'ArrayCache']`  | `withArray => 'fast'` |
| `long` | `['*memory*', 'SqlGroup', 'ArrayCache']` | (none) |
| `long+` | `['*memory*', 'SqlGroup', 'ArrayCache']` | `withArray => TRUE` |
| `long++` | `['*memory*', 'SqlGroup', 'ArrayCache']` | `withArray => 'fast'` |

**Comment by eileenmcnaughton** [comment]
I would probably argue for one of these

* Simply update the existing `short` and `long` to set `withArray => TRUE`
* Simply update the existing `short` and `long` to set `withArray => 'fast'`

since that brings us closest to the functionality we are deprecating (the old path) & people could switch pattern without adverse performance effects

**Comment by totten** [comment]
> ... since that brings us closest to the functionality we are deprecating (the old path) ...

This a good point, though I'd like to flesh out a little for clarity:

* Re:`long` cache -- A typical (non-Redis) deployment is actually using `SqlGroup`. The common `[type=>SqlGroup]` and less common  `[type=>*memory*, withArray=>TRUE]` have the same characteristics wrt cache-coherency. (*In both, the thread-local array may retain dirty data for cache-lines that have been modified or unset by a concurrent thread. In both, TTLs are respected.*)
* Re: `short` cache -- A typical (non-Redis) deployment is actually using `ArrayCache`.  The common `[type=>ArrayCache]` has cache-coherency that  is more comparable to `[type=>*memory*, withArray=>TRUE]`. (*In both cases, the thread-local array may retain dirty data for cache-lines that have been modified or unset by a concurrent thread. In both, TTLs are respected.*)

Of course, if the default behavior is changed to `withArray=>TRUE`, then one may need some special accommodation to flush the cache during upgrade (b/c the pre-upgrade cache would have a different storage format than the post-upgrade cache).

**Comment by eileenmcnaughton** [comment]
@totten I'm just looking at this again because I want to do some caching in an extension

It seems like at the moment just using Civi::cache() doesn't make sense with Redis because the 'normal' should be Civi::cache('withArray' => 'fast'); 

If we are feeling conservative about this I think we should maybe just use a define opt in since we already do that here https://github.com/civicrm/civicrm-core/commit/5a302bbc2f3bd75b28401667f48966d65a4a0b36#diff-16851badbd9585cd777291608d9f2dccR464

Or just read into that define the desire to use withArray
