### ISSUE TITLE
Self-referential link on page is confusing

### ISSUE THREAD

**Issue by jptillman** [civicrm/civicrm-dev-docs#577]
3rd bullet point under "Extensions" header has a broken link:

"For instructions, see Extensions."

It's trying to link to this page:

https://github.com/civicrm/civicrm-dev-docs/blob/master/extensions/index.md

What's worse is that the link appears to be attempting to access the exact same page it's on, rendering it useless even if it did work.

On a general note, this is the 3rd broken link and 2nd confusing statement that I've come across in 5 minutes of trying to read up on Civi extension building.  The state of this documentation set is terrible.

**Comment by jptillman** [comment]
It seems that a global relocation of files has broken nearly every link in the markdown of this documentation set.  Files have been moved into a "docs" subdirectory, but the links have not been updated.

**Comment by seamuslee001** [comment]
@jptillman no, its done that way deliberately so markdown docs that serve the page here https://docs.civicrm.org/dev/en/latest/ the links in github aren't meant to be directly navigated but are to be processed when publishing the page. If you clone the repo locally and install mkdocs and run `mkdocs serve` then you should find it shows no errors

**Comment by jptillman** [comment]
Oh, I see.  Then the documentation at this site is the source of all the trouble:
https://docs.civicrm.org/dev/en/latest/extensions/
They are linking directly to your content, sending anyone looking for info on extension building to a broken documentation set.  I'll see if I can find a way to report that.

**Comment by jptillman** [comment]
Actually, there's still an issue with the self-referential link.  That's worth fixing to avoid confusion.
