### ISSUE TITLE
Update extension review process

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-dev-docs#606]
I want to get https://civicrm.org/extensions/the-the approved but the docs say to log a JIRA issue....

**Comment by joemcl** [comment]
Related to #520

**Comment by joemcl** [comment]
So this is 'fixed' with this right? - https://lab.civicrm.org/extensions/extension-review-requests/issues ?

**Comment by twomice** [comment]
Request to close.
