### ISSUE TITLE
Migrate content from multiple sources about "Contributing"

### ISSUE THREAD

**Issue by seancolsen** [civicrm/civicrm-dev-docs#61]
There's some good documentation here about contributing to CiviCRM using GitHub. 

https://github.com/civicrm/civicrm-core/blob/master/.github/CONTRIBUTING.md

I'd like to move this content into the Dev Guide. @totten is it important that we keep that `CONTRIBUTING.md` file in place? If so, then can we wipe its contents and instead use some brief text that links readers to the new content within the Dev Guide?

**Comment by seanmadsen** [comment]
When we pull this page in, we should also include examples of good and bad commit messages shown on 

https://wiki.civicrm.org/confluence/display/CRMDOC/Git+Commit+Messages+for+CiviCRM

as well as any other useful content within: 

https://wiki.civicrm.org/confluence/display/CRMDOC/Contributing+to+CiviCRM+using+GitHub

Then, both of those wiki pages should redirect to this one new page.

**Comment by seanmadsen** [comment]
also incorporate some content from this, and maybe link to it: 

http://blogs.atlassian.com/2016/07/written-unwritten-guide-pull-requests/

**Comment by MikeyMJCO** [comment]
Closing this issue. If there is still work to do on this subject it'll likely need new smaller issues/PRs.
