### ISSUE TITLE
update phpunit version info

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-dev-docs#611]
The docs say buildkit ships with phpunit4 but I think this is out of date.

For the record to avoid errors about PHPUnit_Extensions_Database_TestCase on php 7.2 I had to use the following in composer.json

```
{
    "require": {
      "phpunit/dbunit": "~2",
      "phpunit/phpunit": "~5"
    }
}
```

Officially phpunit 5 doesn't work with php 7.2 	https://phpunit.de/supported-versions.html
but it's the only combo I could get working

**Comment by eileenmcnaughton** [comment]
Update - we have removed the need to dbunit - yay. I think in general phpunit 6 is recommended now

**Comment by eileenmcnaughton** [comment]
if I comment will it go

**Comment by MikeyMJCO** [comment]
No, I didn't update this to v3 yet :-p one sec!

**Comment by MikeyMJCO** [comment]
Now it should :-)

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO when does it run

(@kartik1000 )

**Comment by MikeyMJCO** [comment]
On the hour!

**Comment by MikeyMJCO** [comment]
Sorry, hadn't realised that there's a config option for it (not well documented yet!)

```yml
  removeStaleWhenUpdated: true
```

**Comment by MikeyMJCO** [comment]
Okay, updated to run every 5th minute and added that config option, let's see if this works!

**Comment by MikeyMJCO** [comment]
We're gonna have to wait for it to get past the rate limiting and per-run limit I think - so it may take a while to get to this issue (if it works!)

**Comment by MikeyMJCO** [comment]
I may, or may not, have disabled actions whilst testing something!

**Comment by MikeyMJCO** [comment]
Aha! It worked!

**Comment by eileenmcnaughton** [comment]
Tangentally - I can't see where the ref to phpunit4 is - maybe it's fixed

**Comment by MikeyMJCO** [comment]
Following your inappropriate tangent 😛 yeah - it's been fixed :-)
