### ISSUE TITLE
Migrate content from civicrm-core/docs

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#62]
There are 9 markdown files here with content relevant to the Dev Guide

https://github.com/civicrm/civicrm-core/tree/master/docs

On first glance it appears unlikely that any new content will exist in this location, but we should comb though it to reconcile anything useful for import.

**Comment by totten** [comment]
They're stale. Those file were my skeleton for a mkdocs-based dev guide; Michael subsequently setup a new repo and took it in another direction. For now, I think you can just do a PR to delete the old skeletal docs.

**Comment by seanmadsen** [comment]
Created PR here: https://github.com/civicrm/civicrm-core/pull/9771

**Comment by seanmadsen** [comment]
Closing this issue since there is no further action needed within the Dev Guide
