### ISSUE TITLE
Document how new private file paths work

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-dev-docs#651]
Document https://github.com/civicrm/civicrm-core/pull/14718 - follow on is here
https://lab.civicrm.org/dev/core/issues/1148

**Comment by herbdool** [comment]
I was thinking we also document the change for sysadmins who might need to set the paths. Not sure best place to put it. This https://docs.civicrm.org/sysadmin/en/latest/customize/settings/ is not the exact place.

**Comment by MikeyMJCO** [comment]
Resolved with #652
