### ISSUE TITLE
[meta] Test all links, update where necessary

### ISSUE THREAD

**Issue by joemcl** [civicrm/civicrm-dev-docs#679]
Determine the 'best' way to test all links to external site refererences in this docs repo ( and the other docs repos ) and fix/update broken links. This is a 'meta' issue right, don't know if I can add that label or if it exists here yet.

**Comment by MikeyMJCO** [comment]
New docs publisher code will handle this and reject publishing if it gets a bad http error code.

**Comment by MikeyMJCO** [comment]
Needs a test case for docs publisher - will make a note for sprint!

**Comment by joemcl** [comment]
@MikeyMJCO do you mean when we move these to GitLab, or new docs publisher in GitHub? Either way, seems worth getting started here while GitLab transition gets figured out.... Also, how to detect not just broken but wrong/ potentially malicious links, like what drush was pointing to.

**Comment by MikeyMJCO** [comment]
The new [docs publisher](https://lab.civicrm.org/documentation/docs-publisher) code will be live by the end of the sprint (hopefully!) and will fix this issue!

**Comment by joemcl** [comment]
Ok cool

**Comment by MikeyMJCO** [comment]
Closing - tbc on Lab

**Comment by joemcl** [comment]
Hey @MikeyMJCO can you reopen this and let me close it when we actually *resolve* the Issue :) ? Thanks.

**Comment by MikeyMJCO** [comment]
> Hey @MikeyMJCO can you reopen this and let me close it when we actually _resolve_ the Issue :) ? Thanks.

I'd rather not, it's in completely the wrong place. This repo is for the docs dev book only - happy to have an open issue on this on GitLab against the docs-publisher or in the docs meta repos there :-) there will also be more visibility there on Lab as that's where the docs meta discussions take place...
