### ISSUE TITLE
Migrate hooks into separate pages

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#71]
As discussed in #52 we'd like to put hooks in the Dev Guide and use one page per hook as follows: 

`https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_merge#parameters`

- Each hook has its own markdown file
- H1 is used for hook name
- H2 is used for hook *sections*
- Hooks markdown files are all stored within one folder `hooks` (i.e. *not* categorized at the folder level - which makes it possible to re-categorize hooks later on, which might happen given that there are currently a lot of "uncategorized" hooks.)
- The navigation menu uses one folder for hooks, then sub-folders within that for *categories*. 
    - Note: if we decide later on that we don't like the deep navigation structure here, we can make the change within the menu but still keep markdown files stored in the same folder to preserve URLs. MkDocs is fine with this. 

We'd like to do this migration atomically for all hooks at the same time if possible.

**Comment by seanmadsen** [comment]
@totten @ErichBSchulz @michaelmcandrew @nganivet 

I'm excited to announce that I've made some progress on migrating the hooks! Before I make a PR, I'd like to get some feedback on the current state of my migration, which I'm doing in the `hooks-op-4` branch of this repo. 

You can actually **view it live** here: https://docs.civicrm.org/dev/en/hooks-op-4/

One thing still to-do is to take the old Dev Guide page at `/hooks-db` which has a woefully incomplete listing of hooks, and merge this content into the separate hooks pages. 

What do people think of this migration with option 4 (each hook on its own page)? 

So far, I really like it. The navigation menu is more usable than I thought it would be. 

Because I'm doing the migration with a script, it's easy to change things en masse if needed.

**Comment by seanmadsen** [comment]
Note: if you spot something in the test migration of hooks that you don't like, there are three ways to address it: 

1. Change content in the wiki, so that when I re-run the migration, it gets fixed
1. Change the migration script to be smarter about migrating the content 
1. Create an issue to clean content after it is finally migrated (I've already made a few of these.)

Note that editing the markdown is not an option because the "final" migration has not yet been performed.

**Comment by ErichBSchulz** [comment]
Hey sorry I missed this @seanmadsen! wow looks awesome

I think  this worth flagging in the #dev channel and asking for feeback

superficially this looks **great** to me - but good to get the core team to really give this a good look at I reckon

**Comment by michaelmcandrew** [comment]
Brilliant :) and loving the URL structure :)

Wondering what it looks like with material?
