### ISSUE TITLE
Document process for abandoned Extensions, with either someone taking over the extension maintainer role or de-listing the extension

### ISSUE THREAD

**Issue by jusfreeman** [civicrm/civicrm-dev-docs#730]
Document process for abandoned Extensions, with either someone taking over the extension maintainer role or de-listing the extension.

This should also include a process for reporting an abandoned extension and the process to be followed for either de-listing or transferring maintainers.

The documentation on Extension Lifecycle is deficient, there is no recognition of an extension being "abandoned" as is this case with the ChrisChinchilla/CiviCRM-eWay-recurring-payment-processor, see https://github.com/ChrisChinchilla/CiviCRM-eWay-recurring-payment-processor/issues/59

Abandoned software is a common occurrence, as you will have no doubt seen in other open source communities such as Drupal and WordPress.

Drupal, https://www.drupal.org/node/251466
WordPress, https://developer.wordpress.org/plugins/wordpress-org/take-over-an-existing-plugin/

Relates to this discussion, https://lab.civicrm.org/extensions/extension-review-requests/issues/11

Agileware Ref: CIVICRM-1375

**Comment by mlutfy** [comment]
Current policy: https://lab.civicrm.org/extensions/extensions-directory/wikis/extension-removal-process

(which might evolve in the next days, since we only had a few rare cases to work from, and one is ongoing)

**Comment by twomice** [comment]
As stated elsewhere, I'd like to see that wiki doc linked more visibly from Extension Lifecycle docs, if someone wants to take a stab at a PR there.

**Comment by MikeyMJCO** [comment]
See #731

**Comment by MikeyMJCO** [comment]
#731 is merged now - do we (collectively) feel like that's enough or should we keep this issue open with a view to improving the information in the docs to replicate the information from the Wiki?

**Comment by twomice** [comment]
I'm unclear of the intended relationship between wiki and docs, i.e., not sure why they co-exist or what they're separate purposes/domains are.

**Comment by jusfreeman** [comment]
@MikeyMJCO @twomice thank you

It would make sense to consolidate the CiviCRM Developer documentation and have a single point of reference. So I would be strongly in favour of having all the documentation in https://github.com/civicrm/civicrm-dev-docs to avoid maintaining two sets of docs (github & lab.civicrm/wiki)

**Comment by mlutfy** [comment]
yep, I tend to create wiki pages for WIP docs, but they are more discoverable if they are in the official docs.

**Comment by jusfreeman** [comment]
Sounds like we have an agreement then, the canonical source should be https://github.com/civicrm/civicrm-dev-docs

**Comment by jusfreeman** [comment]
PR has been submitted to incorporate the wiki with CiviCRM Dev Docs, so I'll close this issue now.

**Comment by jusfreeman** [comment]
@mlutfy FYI, these wiki pages can be removed now:
https://lab.civicrm.org/extensions/extensions-directory/wikis/extension-maintainer-transfer-process
https://lab.civicrm.org/extensions/extensions-directory/wikis/extension-removal-process

PR has been merged, https://github.com/civicrm/civicrm-dev-docs/pull/736
