### ISSUE TITLE
rationalise build instructions

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/civicrm-dev-docs#76]
good insights from Tim here:

https://chat.civicrm.org/civicrm/pl/dxhs8b9m5f8wtmnu9fdz7gehja

@seanmadsen Sean if you want to capture this go for it. Otherwise ping me when you want me to have a go.

**Comment by seanmadsen** [comment]
I'm not really sure what needs to happen here. @ErichBSchulz can you offer some clarification? 

Seems like the page in question is [this one](https://docs.civicrm.org/dev/en/master/develop/) which I think is pretty much being phased out and made irrelevant by other docs improvements. My hunch here (after only spending a couple minutes looking) is that we can close this issue and move on, with some trust that this content will get cleaned up during the plan to [improve buildkit docs](https://github.com/civicrm/civicrm-buildkit/issues/313). Okay to close, Erich?

**Comment by ErichBSchulz** [comment]
ok
