### ISSUE TITLE
Correcting a typo in extension directory structure

### ISSUE THREAD

**Issue by asha15** [civicrm/civicrm-dev-docs#768]
Extension directory structure provide an example to store BAO files. It states the BAO files should go `CRM_Myextension\BAO\` , but it should be `CRM\Myextension\BAO\`

I would like to work on this issue.

**Comment by MikeyMJCO** [comment]
Good catch. Submit a PR to fix and we'll absolutely get that merged.

**Comment by asha15** [comment]
Thank you! I'll send a PR

**Comment by MikeyMJCO** [comment]
PR merged - thank you @asha15

**Comment by asha15** [comment]
@MikeyMJCO  It's my pleasure :)
