### ISSUE TITLE
Correcting the path in 'Generate a skeletal extension'

### ISSUE THREAD

**Issue by asha15** [civicrm/civicrm-dev-docs#770]
In **Generate a skeletal extension** section, it provides two paths to activate the extension created by user. They are

> Administer » System Settings » Manage Extensions
> or
> Administer » Customize Data and Screens » Manage Extensions.

But it should be 
> Administer » System Settings »  Extensions

Link for the page: https://docs.civicrm.org/dev/en/latest/extensions/civix/

**Comment by MikeyMJCO** [comment]
Well spotted. Submit a PR to fix please if you can :-)

**Comment by asha15** [comment]
@MikeyMJCO Sure , I'll submit a PR

**Comment by MikeyMJCO** [comment]
PR merged - thanks @asha15
