### ISSUE TITLE
How to prepare your PR for the release notes author

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-dev-docs#787]
https://docs.civicrm.org/dev/en/latest/core/contributing/ and https://docs.civicrm.org/dev/en/latest/core/release-process/ don't cover how to prepare your PR for the release notes author

@agh1 gave a fairly good summary of what you need to do here: https://lab.civicrm.org/dev/core/-/issues/1331#note_33813 in the context of that specific issue.

Tangential: are there other things that are necessary or worthwhile doing as part of this process?

**Comment by MikeyMJCO** [comment]
I like what @agh1 gave on that issue. It's a good starting point!
