### ISSUE TITLE
Redirecting to the incorrect URL 

### ISSUE THREAD

**Issue by asha15** [civicrm/civicrm-dev-docs#815]
In the Debugging -> Viewing log files section providing a incorrect URL to view the file system documentation 

current link :https://docs.civicrm.org/framework/filesystem.md
The link should be: https://docs.civicrm.org/dev/en/latest/framework/filesystem

**Comment by MikeyMJCO** [comment]
Can you try and provide links to the page that has the bad link in future please!

**Comment by asha15** [comment]
@MikeyMJCO Sure. I'll send a PR

**Comment by MikeyMJCO** [comment]
Fixed in PR #816
