### ISSUE TITLE
Make URLs hackable

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#86]
@michaelmcandrew [suggested](https://chat.civicrm.org/civicrm/pl/djwzt96epbnrzbfddcxxicduoo) that we move `/docs/hook.md` to `/docs/hooks.md` to support URL hacking. (Example: if a visitor arrives at `/hooks/hook_civicrm_copy` then they can delete `hook_civicrm_copy` to arrive at `/hooks` which would be an actual page)

This is a cool idea. I just tested it, and to my surprise, it actually works (I wasn't sure if MkDocs would build the site with this setting). 

I think before we go forth with this approach, it's worth considering: 

* Does MkDocs have a better solution for allowing people to hack the URLs? Do they have a way to automatically make a landing page out of a folder, or redirect from a folder to the first landing page within it?
* If we do this for the hooks pages, should we do it for the other pages as well? Is consistency important here?

**Comment by michaelmcandrew** [comment]
> Does MkDocs have a better solution for allowing people to hack the URLs? Do they have a way to automatically make a landing page out of a folder, or redirect from a folder to the first landing page within it?

I don't think so.

> If we do this for the hooks pages, should we do it for the other pages as well? Is consistency important here?

I think that documenting that we want to follow this principle is the best we can do (aside from improving mkdocs to run a test to see that all parent URLs are present, which seems a little beyond our resources).

**Comment by seanmadsen** [comment]
**Next steps:** 

1. Improve docs-publisher to [allow internal redirects](https://lab.civicrm.org/documentation/docs-publisher/issues/20)
1. Add content to the [style guide](https://docs.civicrm.org/dev/en/master/best-practices/documentation-style-guide/) (somewhere) which describes our intent to create hackable URL's, where possible. 
1. Look through the Dev Guide to identify places where we can make URL's more hackable. For example, the path `/api/general/` could be changed to `/api/`
1. List changes needed within this ticket
1. Make the changes listed, being sure to create page redirects along the way
