### ISSUE TITLE
Rename API parameters chapter to API options

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-dev-docs#92]
Apart from the first sentence and the last section on custom data, the [API parameters](https://docs.civicrm.org/dev/en/master/api/params/) chapter is actually covering API options (sequential is arguably an option that does not follow the conventional naming).

Hence, I suggest:

1. renaming that chapter to options and
2. moving the last section on custom data into its own section API custom data (where you could also talk about the APIs that relate to custom data CustomField, CustomGroup, CustomValue and also OptionGroup and OptionValue to the extent that they relate to creating custom data).

**Comment by totten** [comment]
👍 

Also suggest "3. Rewrite the intro paragraph". The current intro is redundant with the "API Intro" page and would be a bit different for "API Options".

**Comment by seanmadsen** [comment]
Resolved with #262
